prefix as: <http://www.w3.org/ns/activitystreams#>
prefix dc: <http://purl.org/dc/elements/1.1/>
prefix dct: <http://purl.org/dc/terms/>
prefix dctypes: <http://purl.org/dc/dcmitype/>
prefix foaf: <http://xmlns.com/foaf/0.1/>
prefix iiif_prezi: <http://iiif.io/api/presentation/3#>
prefix iiif_image_3: <http://iiif.io/api/image/3#>
prefix mf: <https://api.meemoo-int.triply.cc/queries/milan/iiif-glassplate-manifest/1/run#>
prefix oa: <http://www.w3.org/ns/oa#>
prefix org: <http://www.w3.org/ns/org#> 
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix prov: <http://www.w3.org/ns/prov#>
prefix schema: <https://schema.org/>
prefix haLic: <https://data.hetarchief.be/id/license/>
prefix mh: <https://data.hetarchief.be/ns/mediahaven/>
prefix haObj: <https://data.hetarchief.be/ns/object/>
prefix haOrg: <https://data.hetarchief.be/ns/organization/>
prefix rel: <http://id.loc.gov/vocabulary/preservation/relationshipSubType/>
prefix premis: <http://www.loc.gov/premis/rdf/v3/>
prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>


CONSTRUCT {
  ?manifestIri a iiif_prezi:Manifest;
                rdfs:label ?titleNl ;
                as:items ?canvasIri .

  ?canvasIri a iiif_prezi:Canvas ;
             as:items ?annotationPageIri .

  ?annotationPageIri a as:OrderedCollectionPage ;
                     as:items ?annotationIri .

  ?annotationIri a oa:Annotation ;
                oa:motivatedBy "painting" ;
                oa:hasTarget ?canvasIri ;
                oa:hasBody ?bodyIri .
  
  ?bodyIri a dctypes:StillImage ;
            dc:format "image/jpeg" .
}
WHERE {
  ?s prov:wasDerivedFrom ?mhRecord ;
     schema:identifier ?pid ;
     schema:license ?license ;
     schema:name ?title ;
     haObj:hasIIIFCopy ?iiifRepresentation .
      
  ?mhRecord mh:fragmentIdentifier ?fragmentId .

  ?iiifRepresentation rel:inc ?iiifFile .

  ?iiifFile premis:storedAt ?iiifFileLocation .

  ?iiifFileLocation rdf:value ?iiifFileUrl .
  
  FILTER (?license IN (haLic:IIIF-PUBLIC))

  #  IIIF structure IRIs
  BIND(IRI(CONCAT("https://iiif.meemoo.be/presentation/3/", ?pid, "/manifest.json")) AS ?manifestIri)
  BIND(IRI(CONCAT("https://iiif.meemoo.be/presentation/3/", ?pid, "/canvas/1")) as ?canvasIri)
  BIND(IRI(CONCAT("https://iiif.meemoo.be/presentation/3/", ?pid, "/canvas/1/page/1")) as ?annotationPageIri)
  BIND(IRI(CONCAT("https://iiif.meemoo.be/presentation/3/", ?pid, "/canvas/1/page/1/annotation/1")) as ?annotationIri)
  BIND(IRI(CONCAT(STR(?iiifFileUrl),".jph")) AS ?serviceIri)
  BIND(IRI(CONCAT(STR(?serviceIri), "/full/max/0/default.jpg")) AS ?bodyIri)

  #  Specific values
  BIND(IF(LANG(?title) = "nl", ?title, 1/0) AS ?titleNl)
}